services:
  mongodb:
    image: mongo:7
    container_name: rizzbo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: rizzbo

volumes:
  mongo_data: